services:
  postgres:
    image: postgres:15
    container_name: nexa_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_DB: nexaledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: nexa_redis
    restart: always
    ports:
      - "6379:6379" # Redis communication port

volumes:
  postgres_data:
